# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWrapped < Formula
  desc "Spotify Wrapped, but for your GitHub year"
  homepage "https://github.com/vaibhav0806/git-wrapped"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaibhav0806/git-wrapped/releases/download/v0.1.1/git-wrapped_darwin_amd64.tar.gz"
      sha256 "c83406a82d49a616866c4efb6afb9f0555b4c0670d2c8b2c658353db8c6b0cb8"

      define_method(:install) do
        bin.install "git-wrapped"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaibhav0806/git-wrapped/releases/download/v0.1.1/git-wrapped_darwin_arm64.tar.gz"
      sha256 "2db94fa7b42427e80664bef4ce582ec54871ccc34e2b5867f765d1ab4cfd4d43"

      define_method(:install) do
        bin.install "git-wrapped"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/git-wrapped/releases/download/v0.1.1/git-wrapped_linux_amd64.tar.gz"
      sha256 "1fc2e4d195ee7294a571a0b422933ccd87e594a7dd6492570836742f2898fe0d"
      define_method(:install) do
        bin.install "git-wrapped"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/git-wrapped/releases/download/v0.1.1/git-wrapped_linux_arm64.tar.gz"
      sha256 "bcf83e1e2d6c4bb2eabaa36f9b158f3f034fe86d267c9cad545be9ef223aba96"
      define_method(:install) do
        bin.install "git-wrapped"
      end
    end
  end
end
