# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PixelTamagotchi < Formula
  desc "A tamagotchi cat that lives in your terminal"
  homepage "https://github.com/vaibhav0806/pixel-tamagotchi"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.1/pixel-tamagotchi_darwin_amd64.tar.gz"
      sha256 "af39088bfb23a6714f5b471c57a06ef5a539c85f7c17cb6b1260ac7f28ee134d"

      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.1/pixel-tamagotchi_darwin_arm64.tar.gz"
      sha256 "98932f5903a0a8a0876cf4c56081308e435aef89e476842c4e5c90d894fabd4f"

      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.1/pixel-tamagotchi_linux_amd64.tar.gz"
      sha256 "aca5f4ec9c949bd9a61c7851ce0e4cb1b1326f2146ea29d0453646ed1f12d1c2"
      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.1/pixel-tamagotchi_linux_arm64.tar.gz"
      sha256 "63168f601b295d575b173a613a6bfe653c1c7a66344fb040840d7c42ba8854ac"
      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
  end
end
