# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PixelTamagotchi < Formula
  desc "A tamagotchi cat that lives in your terminal"
  homepage "https://github.com/vaibhav0806/pixel-tamagotchi"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.2/pixel-tamagotchi_darwin_amd64.tar.gz"
      sha256 "fcf7f30a92f7a99b87169f2c5ce9affedc16da8a54e7843a90ab505a9dbc8da5"

      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.2/pixel-tamagotchi_darwin_arm64.tar.gz"
      sha256 "d55e188cc301160ffe6dc6066c3214a9de5f1fe19f892745a7fccf2a365c41c6"

      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.2/pixel-tamagotchi_linux_amd64.tar.gz"
      sha256 "6590727b2aefce5e2ec274fe0aff5b3d6be19e3a8decf09e6391bb145da1a3c3"
      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.4.2/pixel-tamagotchi_linux_arm64.tar.gz"
      sha256 "fb921d3b6ee94c9e718789da21d5d99e893ec836bb45177fcb2123c133997b34"
      define_method(:install) do
        bin.install "pixel-tamagotchi"
        bin.install_symlink "pixel-tamagotchi", "pixel"
      end
    end
  end
end
