# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PixelTamagotchi < Formula
  desc "A tamagotchi cat that lives in your terminal"
  homepage "https://github.com/vaibhav0806/pixel-tamagotchi"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.3.1/pixel-tamagotchi_darwin_amd64.tar.gz"
      sha256 "ffc1e572e2331eca687afe4934a15b3022aa1a2442801149fe8e8f4a76aa883a"

      define_method(:install) do
        bin.install "pixel-tamagotchi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.3.1/pixel-tamagotchi_darwin_arm64.tar.gz"
      sha256 "b5668ffa524556130a82ff45d3f383f23eebfcfe257375f546925a25eec34d25"

      define_method(:install) do
        bin.install "pixel-tamagotchi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.3.1/pixel-tamagotchi_linux_amd64.tar.gz"
      sha256 "b595c1d112e56c5fab14fcf39252f6ebcba9c1b1a3bdc72d7d8466f0de74f0bc"
      define_method(:install) do
        bin.install "pixel-tamagotchi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vaibhav0806/pixel-tamagotchi/releases/download/v0.3.1/pixel-tamagotchi_linux_arm64.tar.gz"
      sha256 "661db9dc8cbd705068a57bdeb739f96c5b394b1d1096c39e9bd4e6e55046ae4a"
      define_method(:install) do
        bin.install "pixel-tamagotchi"
      end
    end
  end
end
